### PR TITLE
Compatibility with native Poseidon sponge

### LINKED ISSUE #95: `PoseidonChip` compatibility
Do you know whether the `PoseidonChip` is meant to be spec compatible with the native one? Perhaps I'm doing something wrong, but the following fails for me (Scroll's impl claims to be "in line with the reference and the test vectors"):

```Cargo.toml
poseidon-native = { git = "https://github.com/scroll-tech/poseidon/", package = "poseidon"}
poseidon = { git = "https://github.com/axiom-crypto/halo2-lib", branch = "community-edition" }
```

```rust
let gate = GateChip::<F>::default();

let mut sponge = PoseidonChip::<F, T, RATE>::new(ctx, R_F, R_P).unwrap();
let assigned = sponge.squeeze(ctx, &gate).unwrap();

let mut native_sponge = poseidon_native::Poseidon::<F, T, RATE>::new(R_F, R_P);
let native = native_sponge.squeeze();

assert_eq!(assigned.value(), &native); // this fails
```

I know that you guys got inspiration for the `PoseidonChip` from the scroll sponge, so apologies if this is completely the wrong place for this issue, but at least I can run meaningful tests between the native & in-circuit Poseidon sponge using your repo 🙏🏼  (as the Scroll halo2-snark-aggregator is a little out of date).

Also @zhenfeizhang @noel2004

### PR DESCRIPTION
**Pull request by Antonio95**
Closes #95 

This sponge is not compatible with other existing native Poseidon sponges - by native I mean executed directly as Rust code, rather than inside a Halo 2 circuit. Specifically, our native reference is [https://github.com/scroll-tech/poseidon/](https://github.com/scroll-tech/poseidon/).

The issue boils down to [line 54](https://github.com/axiom-crypto/halo2-lib/blob/community-edition/hashes/poseidon/src/lib.rs#L54) of the function `absorb_with_pre_constants`. Judging by other implementations, the input should not be added to the first element of the state (which I interpret as the capacity). Furthermore, the current code skips pre-constant addition to the capacity if the input is empty, which should not be the case.

Replacing the cited line by one which just adds the pre-constant to that first position makes this implementation perfectly compatible with the referenced native sponge. This has been tested in various forms: only squeezing, only absorbing and interleaved absorptions and squeezings. I must admit this tests have only taken place with the standard parameters `T = 3, RATE = 2, ROUNDS_FULL = 8, ROUNDS_PARTIAL = 57`.

### CODE REVIEW

File: hashes/poseidon/src/lib.rs [hunk 1]
```diff
@@ -51,15 +51,31 @@ impl<F: ScalarField, const T: usize, const RATE: usize> PoseidonState<F, T, RATE
...
+        //   to as many elements as inputs are available.
+        // - To the first element for which no input is left (if any), an extra 1 is added.
+
+        // ORIGINAL CODE: CAUSED PROBLEMS
+        // self.s[0] =
+        //     gate.sum(ctx, inputs.iter().map(|a| Existing(*a)).chain([Constant(pre_constants[0])]));
+
+        // adding preconstant to the distinguished capacity element (only one)
+        // REPLACED BY THIS
+        self.s[0] = ctx.load_witness(*self.s[0].value() + pre_constants[0]);
```
Comment (jonathanpwang) [inline hashes/poseidon/src/lib.rs:69]: This would load it entirely as witness, without any constraints. 
Instead you should do `self.s[0] = gate.add(ctx, self.s[0], Constant(pre_constants[0]));`

**Review by jonathanpwang — CHANGES_REQUESTED** [review]
Thanks for finding this! Helps close a big mystery. 

I checked and it does match the audited version here: https://github.com/axiom-crypto/snark-verifier/blob/43e95ce63a65e9de5843a6e0b994b3b3e7da618c/snark-verifier/src/util/hash/poseidon.rs#L365C7-L365C7 
so indeed this version had a typo.

The suggested fix is currently under-constrained at the circuit level. I have suggested a fix in the comments.

File: hashes/poseidon/src/lib.rs (hunk 1 above)
Comment (Antonio95) [reply hashes/poseidon/src/lib.rs]: Thank you so much! I found the logical flaw but failed to constrain it on the circuit level. I have now pushed a corrected version according to your suggestion.

**Comment by jonathanpwang** [comment]
It would also be nice if you could write a test (following example style in `gates/tests` or `zkevm-keccak`) to show that the circuit output now matches the native output (I think it should also match the primitives/poseidon version we import now). You can then add the test to the `github/workflows/ci.yaml`

**Comment by Antonio95** [comment]
Tests have now been added for compatibility
- when squeezing only
- when absorbing only (save for one necessary final squeeze to verify equality of states)
- when interleaving calls to squeeze and absorb
- when using different parameters than the standard (3, 2, 8, 57)

All passing!

File: hashes/poseidon/src/tests.rs [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+        let mut list = Vec::new();
+        for _ in 0..len {
+            list.push(rng.gen_range(0..=max));
+        }
+        list
+    }
+
+    #[test]
+    fn test_poseidon_compatibility_squeezing_only() {
+        let absorptions = Vec::new();
```
Comment (jonathanpwang) [inline hashes/poseidon/src/tests.rs:90]: If absorptions is empty, will the zip in the test just skip all squeezes?

File: hashes/poseidon/src/tests.rs [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+        let squeezings = random_list_usize(10, 7);
+
+        poseidon_compatiblity_verification::<Fr, 3, 2>(absorptions, squeezings, 8, 57);
+    }
+
+    #[test]
+    fn test_poseidon_compatibility_absorbing_only() {
+        let absorptions = random_nested_list_f(8, 5);
+        let squeezings = Vec::new();
```
Comment (jonathanpwang) [inline hashes/poseidon/src/tests.rs:99]: Same zip question as above

File: hashes/poseidon/src/tests.rs (hunk 2 above)
Comment (Antonio95) [reply hashes/poseidon/src/tests.rs:90]: In lines 38-39 of that file, the shorter vector (if there is one) is filled with empty absorptions/squeezings to match the side of the longer one. This was to allow any combination of absorptions and squeezings. It is easy to see that

- a value of 0 in the absorptions list does (literally) nothing - by inspection of my code
- a call to `update` (absorb) on an empty vector does (literally) nothing - by inspection of the sponge code

Comment (jonathanpwang) [reply hashes/poseidon/src/tests.rs:90]: ah, I missed the resize, thanks

**Review by jonathanpwang — APPROVED** [review]
LGTM!

**Comment by Antonio95** [comment]
Thank you!
